/**
 * Curated Lucide icon surface for the marketing site.
 *
 * This is the ONE module allowed to import from `lucide-react` (the ESLint ban
 * is lifted here only). Pages and components import marks from `@/lib/icons`
 * and pass them into DS section props, which render through `<Icon />` from
 * `@azeer/ui` (strokeWidth + size scale locked there).
 */
export {
  ArrowRight,
  Check,
  CheckCheck,
  Zap,
  ShieldCheck,
  Globe,
  Bot,
  BarChart3,
  Workflow,
  Plug,
  Languages,
  Clock,
  Lock,
  MessageSquare,
  MessageCircle,
  Phone,
  PhoneCall,
  Mail,
  Headphones,
  Smartphone,
  Boxes,
  BookOpen,
  FileText,
  Newspaper,
  LifeBuoy,
  GraduationCap,
  Building2,
  Users,
  Sparkles,
  Star,
  BadgeCheck,
  AtSign,
  Rss,
  Moon,
  Sun,
  // Clinic / WhatsApp-revenue surface
  Calendar,
  CalendarCheck,
  CalendarClock,
  CreditCard,
  Wallet,
  Banknote,
  Bell,
  TrendingUp,
  RefreshCw,
  Stethoscope,
  HeartPulse,
  Megaphone,
  MapPin,
  // E-commerce / D2C surface (Salla / Zid)
  ShoppingBag,
  ShoppingCart,
  Store,
  Package,
  Truck,
  Tag,
} from "lucide-react";
